louislam/uptime-kuma-wiki

Reverse-Proxy.md

Hi!
I added some instructions to use uptime-kuma with OpenLiteSpeed.
I did not know how detailed it needed to be so tell me if you think it has to be edited!

OpenLiteSpeed webserver documentation

---

Reverse-Proxy.md

This PR adds information on how to configure HAProxy when using Uptime Kuma.

Added HAProxy as reverse proxy

---

Environment-Variables.md

Creates a nice overview for all the server runtime environment variables.
Link to Issue: https://github.com/louislam/uptime-kuma/issues/355

Document ENV variables

---

OpenRC-Script.md

Alternative to louislam/uptime-kuma#2005

Add OpenRC-Script.md

---

Reverse-Proxy.md

Refs: https://github.com/louislam/uptime-kuma/issues/2375

add IPv6 Support for NGINX reverse proxy

---

🔧-How-to-Install.md

Add sqlite s3 persistent storage via litestream.io

Add sqlite s3 persistent storage

---

Troubleshooting.md

I ran into DNS issues within my container, and managed to resolve them by using the host's network configuration within my Docker container. Updating Troubleshooting.md to point others with the same issue in the right direction :)

Add --network="host" flag explanation/example

---

3rd-Party-Addons.md

Created an xBar plugin to get monitors data from Uptime Kuma and display it on Mac taskbar.

Add plugin to xBarApp for Mac

---

🔧-How-to-Install.md

add Azure AppService with persistent storage using bicep deployment script

add Azure AppService with persistent storage

---

OpenRC-Script.md

- Initialize `kuma.db` if missing, and fix `$directory/data/kuma.db\*` created during `start_pre()` at first run
- Merge log files, and fix `$log_dir/*.log` created during `start_pre()` at first run
- Fix typo

OpenRC-Script.md: initialize kuma.db

---

🔧-How-to-Install.md

Add install Umami on Zeabur tutorial wiki.
referral: https://docs.zeabur.com/marketplace/umami

docs: add install on Zeabur

---

🔧-How-to-Install.md

This PR adds a warning about node 20
In https://github.com/louislam/uptime-kuma/issues/3138 and https://github.com/louislam/uptime-kuma/issues/3202 a few issues have been reported which are breaking for some users.
This PR makes users aware of this issue instead of being frustrated by it.

Warning about node 20

---

🔧-How-to-Install.md

Resolves https://github.com/louislam/uptime-kuma/pull/3594
Additional clean-up needed:
-  Remove [`k8s-unofficial`](https://github.com/louislam/uptime-kuma/tree/k8s-unofficial)
- Close https://github.com/louislam/uptime-kuma/pull/3594

Removed the `k8s-unofficial` section 

---

3rd-Party-Addons-Apps.md

I created this tool for my personal use. I think it may also be needed by others who use the "Push" monitor type.

add tool swatchdog in 3rd-Party-Addons-Apps.md

---

🔧-How-to-Install.md

Adds one click deploy link with Dome

Add one click deploy

---

API-Keys.md
OpenRC-Script.md
Prometheus-Integration.md
Reset-Password-via-CLI.md
Reverse-Proxy.md
Systemd-Unit-File.md
🔧-How-to-Install.md

In some parts of our docs, we did not utilise githubs `NOTE`/... feature
=> this PR changes this
We also did not fully specify what language some code snippits were 
=> this PR adds the languages for better highlighting

Added proper notes and block highlighting

---

Reverse-Proxy-with-Cloudflare-Tunnel.md

I've updated the directions for setting up the Cloudflared tunnels. I didn't know where to host the images, so do with them what you must. 😁

Update Cloudflared tunnel directions

---

🔧-How-to-Install.md

Link to the video was posted here: https://www.reddit.com/r/UptimeKuma/comments/1b43col/uptime_kuma_video_intro/

added a pikapods video to the readme

---

🔧-How-to-Install.md

Let me know if missed anything for this PR

Add Deploy to Fly.io

---

3rd-Party-Addons-Apps.md

Added my Apple Watch application to monitor an Uptime Kuma instance.

Added Uptime Mate to 3rd party apps

---

Reverse-Proxy.md

Made sure the subdirectory note is actually a note

made the reverse proxy subdirectory note into a note

---

Cloudflare-Side-Note.md

Add example how to create a bypass for Kuma with custom header and multiple domains support.

Wiki Cloudflare section update

---

3rd-Party-Addons-Apps.md

Added a new, well used and stable project for Uptime Kuma's Push monitor type.

Update 3rd-Party-Addons-Apps.md with another Uptime Kuma Push Agent

---

Migration-From-v1-To-v2.md

- Various small grammar fixes
- Added table comparing the full / slim container versions

Chore: Improve migration guide wording/grammar

---

Environment-Variables.md

Update Environment-Variables.md: MariaDB only in Version 2

Update Environment-Variables.md: MariaDB only in Version 2

---

API-Documentation.md
_Menu.md
_Sidebar.md

This PR adds comprehensive API documentation to the Uptime Kuma wiki, including:
- Authentication mechanisms for REST and WebSocket APIs
- Common data structures and their formats
- REST API endpoints with request/response examples
- WebSocket event details for both client and server interactions
- Error handling information
The documentation includes a clear warning that this is an internal API that may change without notice, helping to set proper expectations for anyone looking to integrate with Uptime Kuma:
> **⚠️ IMPORTANT NOTE**: This documentation describes Uptime Kuma's internal API. This API is primarily designed for the application's own use and is not officially supported for third-party integrations. Breaking changes may occur between versions without prior notice. Use at your …

Add API Documentation with internal API notice and update navigation

---

3rd-Party-Addons-Apps.md

Successor of #49 after rebranding. I plan to add more advanced monitor types soon :)

feat: add KumaSentinel 3rd party addon

---

3rd-Party-Addons-Apps.md

- [Kuma Mieru](https://github.com/Alice39s/kuma-mieru) - A 3rd-party Uptime Kuma monitoring dashboard built on Next.js, TypeScript and Recharts.

feat: Add Kuma Mieru 3rd-party addon

---

3rd-Party-Addons-Apps.md

Add Home Assistant integration to list of 3rd party apps and addons

Added Home Assistant integration
